<?php
/** @var \Omnipro\RickAndMorty\Block\Template $block */
/** @var \Omnipro\RickAndMorty\ViewModel\RickAndMortyViewModel $viewModel */

//$viewModel = $block->getData("view_model");
$viewModel = $block->getViewModel();
$characters = $viewModel->getCharacters();
?>

<?= __("Rick and Morty Characters") ?>
<br>

<?php foreach ($characters['results'] as $character): ?>
<div class="character">
    <div class="name"><?= $character['name'] ?></div>
    <div class="status"><?= $character['status'] ?></div>
    <div class="species"><?= $character['species'] ?></div>
    <div class="image"><img src="<?= $character['image'] ?>" alt="<?= $character['name'] ?>"></div>
</div>
<?php endforeach; ?>
