<?php

/** @var \Omnipro\Blog\Block\Template $block */


?>



<head>

    <H2>MY SPECTACULAR BLOG</H2>

</head>

    <h>New Blog Post</h>

<br></br>

<form>

    <div class="form-group">

        <input type="text" name="title" placeholder="Titulo">

        <input type="text" name="content" placeholder="Contenido">

        <input type="email" name="email" placeholder="Email">

        <input type="file" name="image" placeholder="Imagen">

        <button class="btn btn-success">Enviar</button>

    </div>

</form>



<br></br>