<?php

/** @var \Magento\Framework\View\Element $block */

$viewModel = $block->getViewModel();
$items = $viewModel->getPosts();
?>

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <link rel="stylesheet" href="../css/Styles.css">
  </head>
  <body>
    <h1 class="main_title">MY SPECTACULAR BLOG</h1>
    <h2 class="subtitle">New Blog Post</h2>
    <main class="main_section">
        <div class="container-form" id="container">
            <form method="POST">
                <input type="text" name="title" placeholder="Titulo" />
                <br><br>
                <textarea name="content" cols="30" rows="15"></textarea>
                <br>
                <input type="email" name="email" placeholder="Email" />
                <br>
                <input type="file" name="image" placeholder="Imagen" />
                <br><br>
                <button class="btn_save">Guardar</button>
            </form>
        </div>
          <div class= "container_b">
            <h1>My lastest post blog</h1> 
            <h3>Aqui va el texto y mas adelante la fecha</h3>
          </div>
          <div class= "container_c">
              <h2>My less recent blog</h2> 
              <h3>Aqui va el texto </h3>
              <img src="">
            </div>
            <div class= "container_d">
                <h2>Today in old news</h2> 
                <h3>Aqui va el texto y atras una imagen</h3>
            </div>
    </main>
    <script>
       function store(){
         let inputEmail= document.getElementById("email");
         let inputContent= document.getElementById("content");
         let inputTitle= document.getElementById("title");
         let inputImage= document.getElementById("image")
         let files = event.target.files; 
         let formData = new FormData();
         formData.append("image",files[0]);
         fetch('https://app.bootcamp.test/rest/V1/omniBlog', {
           method:'POST'
         }).then(response =>response.json())
         .catch(error => {
           console.log(error);
         })
       }
       </script>
  </body>
</html>